### ISSUE TITLE
项目跑步起来啊

### ISSUE THREAD

**Issue by zxmm996** [skyFi/dva-starter#3]
npm install 
npm start 报错

**Comment by skyFi** [comment]
报啥错，能贴出错误日志吗？3q

* 或许，你可以试试npm淘宝镜像
* 需要准备的config文件需要设置好
  * `cd server; cp config.example.js config.js; vim config.js`
* `npm run dev`来运行测试，如果使用`npm start`，需要提供接口，否则会报Ajax错误。

see [https://github.com/skyFi/dva-starter#usage](https://github.com/skyFi/dva-starter#usage)

**Comment by zxmm996** [comment]
@skyFi redis没安好，windows下怎么安装啊

**Comment by skyFi** [comment]
教程应该有很多，可以搜下，或http://m.blog.csdn.net/article/details?id=54970663
